services:
    svelte-app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./:/usr/src/app:rw,cached"
            - "/usr/src/app/node_modules"
        stdin_open: true
        ports:
            - "3000:3000"
        tty: true
        restart: unless-stopped
