declare const api: {
    init: () => Promise<void>;
    launchHoi4: (parameters?: string[]) => void;
    getHoi4Path: () => SteamPath | null;
    getHoi4ExecutablePath: () => string | null;
    getAppLocale: () => string;
    getAppName: () => string;
    isDev: () => boolean;
    getTranslationFiles: () => string[];
    getAllDisplayScreens: () => import('electron').Display[];
    updateScreensList: () => Promise<import('electron').Display[]>;
    folderPathInput: () => Promise<string>;
    isValidHoi4Folder: (path: string) => boolean;
    isValidHoi4ExecutablePath: (path: string) => boolean;
    closeApp: () => void;
    getAppDataPath: () => string;
    logs: () => import('electron-log').LogFunctions;
    openLogsFolder: () => Promise<string>;
    getGameSettings: () => import('./renderer/src/lib/stores/gameSettings').PdxGameSettings | null;
    setGameSettings: (settings: import('./renderer/src/lib/stores/gameSettings').PdxGameSettings) => Promise<void>;
};
